//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nadroga_Arya_College.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_user
    {
        public int user_id { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public string username { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
    }
}
