//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nadroga_Arya_College.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_subject
    {
        public int sub_id { get; set; }
        public string sub_name { get; set; }
    }
}
