//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nadroga_Arya_College.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_test
    {
        public int test_id { get; set; }
        public Nullable<int> sub_id { get; set; }
        public string test_name { get; set; }
        public string total_que { get; set; }
    }
}
