//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nadroga_Arya_College.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentreg
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string othernames { get; set; }
        public string gender { get; set; }
        public string religion { get; set; }
        public string bday { get; set; }
        public string state { get; set; }
        public string LGA { get; set; }
        public string nationality { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string school { get; set; }
        public string faculty { get; set; }
        public string course { get; set; }
        public string level { get; set; }
        public string jamb { get; set; }
        public string sub1 { get; set; }
        public int grade1 { get; set; }
        public string sub2 { get; set; }
        public int grade2 { get; set; }
        public string sub3 { get; set; }
        public int grade3 { get; set; }
        public string sub4 { get; set; }
        public int grade4 { get; set; }
        public int total { get; set; }
        public string appno { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string status { get; set; }
        public string examdate { get; set; }
        public string photo { get; set; }
    }
}
