//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nadroga_Arya_College.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timer
    {
        public int id { get; set; }
        public int studentid { get; set; }
        public string timer1 { get; set; }
    }
}
